apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: todoapp-frontend-dev
  namespace: argocd
spec:
  description: Project for todoapp backend applications
  sourceRepos:
    - https://github.com/KhacThien88/HelmMonolithic
  destinations:
    - namespace: todoapp-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'