appName: todoapp-frontend-dev
env: dev
service:
  port: 2048
  type: ClusterIP

image:
  repository: ktei8htop15122004/todofe-app
  tag: latest
  pullSecret: dockerhub
  pullPolicy: Always

ingress:
  domainName: frontend-dev.khacthienit.click
  path: /
  pathType: Prefix
backend:
  ingress:
    domainDevName: backend-dev.khacthienit.click