appName: todoapp-backend-staging
env: staging
service:
  port: 5000
  type: ClusterIP

image:
  repository: ktei8htop15122004/todo-app
  tag: latest
  pullSecret: dockerhub
  pullPolicy: Always

ingress:
  domainName: backend-staging.khacthienit.click
  path: /
  pathType: Prefix