appName: todoapp-backend
env: dev
service:
  port: 5000
  type: ClusterIP

image:
  repository: ktei8htop15122004/todo-app
  tag: latest
  pullSecret: dockerhub
  pullPolicy: Always

database:
  host: mysql.default.svc.cluster.local
  username: root
  name: tasks_manager
  port: 3306
  secretName: mysql-root-pass
    

ingress:
  domainName: backend-dev.khacthienit.click
  path: /
  pathType: Prefix