apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todoapp-frontend-staging
  namespace: argocd
spec:
  project: todoapp-frontend
  source:
    repoURL: https://github.com/KhacThien88/HelmMonolithic
    path: charts/frontend-server
    targetRevision: main
    helm:
      valueFiles:
        - staging-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace:  todoapp-staging   
  syncPolicy:
    automated:
      selfHeal: true
      prune: true